import type { BotWorldState } from './src/bot/types.js';
import type { AgentCandidate, AgentChoice } from './agent-brain.js';

export type PersistentSolEnvelope={schemaVersion:1;identity:{name:string;bornAt:string};activeTask:string;stateGeneration:number;lastCommittedTick:number;controllerVersion:string};
export type ControllerContext={tick:number;currentTask:string;externalDirective:string|null};
export type ControllerManifest={id:string;version:string;apiVersion:1;capabilities:string[];decisionTimeoutMs:number;registeredAt:string};
export type SolController={id:string;version:string;decide(state:BotWorldState,candidates:AgentCandidate[],context:ControllerContext):Promise<AgentChoice>};
export type ControllerStatus={activeId:string;activeVersion:string;fallbackId:string;pendingId:string|null;pendingVersion:string|null;stateGeneration:number;lastSwitchTick:number;lastError:string|null;activeHealth:{failures:number;decisions:number;timeouts:number;lastDecisionMs:number}};
const valid=(x:any):x is SolController=>!!x&&typeof x.id==='string'&&/^[a-z0-9][a-z0-9._-]{1,63}$/i.test(x.id)&&typeof x.version==='string'&&/^\d+\.\d+\.\d+$/.test(x.version)&&typeof x.decide==='function';
const manifestFor=(c:SolController):ControllerManifest=>({id:c.id,version:c.version,apiVersion:1,capabilities:['decide'],decisionTimeoutMs:20000,registeredAt:new Date().toISOString()});
const fallbackChoice=(candidates:AgentCandidate[],context:ControllerContext,why:string):AgentChoice=>{const rank=(c:AgentCandidate)=>{if(/escape|flee|eat|drink|close|dismiss/i.test(c.label))return 100;if(['survival','recovery'].includes(c.category))return 95;if(c.category==='dialog'||c.category==='modal')return 80;return -1};const candidate=[...candidates].sort((a,b)=>rank(b)-rank(a))[0];if(!candidate||rank(candidate)<0)throw new Error(`LLM unavailable and no emergency action is authorized: ${why}`);return{source:'deterministic',goal:context.currentTask||'Emergency recovery only',reason:`Emergency-only fallback: ${why}`,expectedOutcome:'Resolve immediate danger, then return control to the language model.',actionId:candidate.id,speech:'',confidence:.99,contextKey:'emergency-fallback',fingerprint:candidate.fingerprint};};
export class ControllerRegistry{
 private readonly controllers=new Map<string,SolController>();private readonly manifests=new Map<string,ControllerManifest>();private active:SolController;private pending:SolController|null=null;private lastSwitchTick=-1;private lastError:string|null=null;private generation=0;private health={failures:0,decisions:0,timeouts:0,lastDecisionMs:0};private readonly fallbackId:string;
 constructor(fallback:SolController){if(!valid(fallback))throw new Error('invalid fallback controller');this.fallbackId=fallback.id;this.register(fallback);this.active=fallback;}
 register(controller:SolController,manifest?:Partial<ControllerManifest>){if(!valid(controller))throw new Error('invalid controller module');const key=`${controller.id}@${controller.version}`;const m:ControllerManifest={...manifestFor(controller),...manifest,id:controller.id,version:controller.version,apiVersion:1};if(m.apiVersion!==1||m.decisionTimeoutMs<100||m.decisionTimeoutMs>30000)throw new Error(`invalid controller manifest ${key}`);this.controllers.set(key,controller);this.manifests.set(key,m);return key;}
 stage(id:string,version:string){const next=this.controllers.get(`${id}@${version}`);if(!next)throw new Error(`controller ${id}@${version} is not registered`);this.pending=next;}
 activateAtTick(tick:number){if(!this.pending)return false;this.active=this.pending;this.pending=null;this.lastSwitchTick=tick;this.lastError=null;this.generation++;this.health={failures:0,decisions:0,timeouts:0,lastDecisionMs:0};return true;}
 private isValidChoice(choice:AgentChoice,candidates:AgentCandidate[]){return !!choice&&typeof choice.fingerprint==='string'&&candidates.some(c=>c.fingerprint===choice.fingerprint)&&typeof choice.reason==='string';}
 async decide(state:BotWorldState,candidates:AgentCandidate[],context:ControllerContext){const controller=this.active;const manifest=this.manifests.get(`${controller.id}@${controller.version}`)||manifestFor(controller);const started=Date.now();this.health.decisions++;try{const choice=await Promise.race([controller.decide(state,candidates,context),new Promise<AgentChoice>((_,reject)=>setTimeout(()=>reject(new Error(`controller timeout after ${manifest.decisionTimeoutMs}ms`)),manifest.decisionTimeoutMs))]);this.health.lastDecisionMs=Date.now()-started;if(!this.isValidChoice(choice,candidates))throw new Error('controller returned an illegal or malformed choice');return choice;}catch(err){const text=String(err).slice(0,240);this.lastError=text;this.health.failures++;if(/timeout/i.test(text))this.health.timeouts++;const emergencyCandidates=candidates.filter(c=>['survival','recovery','dialog','modal'].includes(c.category)||/escape|flee|eat|drink|close|dismiss/i.test(c.label));return fallbackChoice(emergencyCandidates,context,text);}}
 get activeController(){return this.active;}
 get status():ControllerStatus{return{activeId:this.active.id,activeVersion:this.active.version,fallbackId:this.fallbackId,pendingId:this.pending?.id||null,pendingVersion:this.pending?.version||null,stateGeneration:this.generation,lastSwitchTick:this.lastSwitchTick,lastError:this.lastError,activeHealth:{...this.health}};}
}
export class PersistentBodyState{readonly envelope:PersistentSolEnvelope;constructor(name:string,controllerVersion:string){this.envelope={schemaVersion:1,identity:{name,bornAt:new Date().toISOString()},activeTask:'Initialize persistent agent',stateGeneration:0,lastCommittedTick:-1,controllerVersion};}commitTick(tick:number,task:string,controllerVersion:string){this.envelope.lastCommittedTick=tick;this.envelope.activeTask=task;this.envelope.controllerVersion=controllerVersion;this.envelope.stateGeneration++;}}
export const createFallbackController=(id='deterministic-fallback',version='1.0.0'):SolController=>({id,version,async decide(_state,candidates,context){return fallbackChoice(candidates,context,'primary controller unavailable');}});
