export type ObligationPhase = 'SURVIVAL'|'STALE_RECOVERY'|'LOOT_RESOLUTION'|'CAPACITY_RESOLUTION'|'TRANSACTION'|'PREREQUISITE'|'OBJECTIVE'|'EXPLORATION';
export type LegalAction = {type:string;[key:string]:unknown};
export type ObligationObservation={hp:number;maxHp:number;inCombat:boolean;freeSlots:number;warningSlots:number;groundItems:Array<{name:string;reachable?:boolean;value?:number}>;bankOpen:boolean;shopOpen:boolean;dialogOpen:boolean;interfaceOpen:boolean;nearbyBank:boolean;nearbyShop:boolean;actionStale:boolean;objectiveActive:boolean};
const junk=/^(ash|bones|empty|junk|weed|coins?)$/i;
const transaction=/^(shopBuy|shopSell|bankDeposit|bankWithdraw|clickDialogOption|closeShop|closeModal)$/;
const unsafeUnderCapacity=/^(attackNpc|worldSkillFishing|fish|shopBuy|bankWithdraw)$/;
export class ObligationExecutor{
 private phase:ObligationPhase='EXPLORATION';private transactionAttempts=0;private noProgressAttempts=0;private lastAction='';private lastProgressTick=0;private blockedUntilTick=0;
 status(){return{phase:this.phase,transactionAttempts:this.transactionAttempts,noProgressAttempts:this.noProgressAttempts,lastAction:this.lastAction||null,lastProgressTick:this.lastProgressTick,blockedUntilTick:this.blockedUntilTick};}
 observe(o:ObligationObservation,tick:number){if(o.hp<=Math.max(8,o.maxHp*.32))this.phase='SURVIVAL';else if(o.actionStale)this.phase='STALE_RECOVERY';else if(o.groundItems.some(i=>i.reachable!==false&&!junk.test(i.name)))this.phase='LOOT_RESOLUTION';else if(o.freeSlots<=o.warningSlots)this.phase=o.bankOpen||o.shopOpen||o.dialogOpen?'TRANSACTION':'CAPACITY_RESOLUTION';else if(o.objectiveActive)this.phase='OBJECTIVE';else this.phase='EXPLORATION';if(tick>=this.blockedUntilTick&&this.noProgressAttempts>=2&&this.phase==='TRANSACTION')this.phase='STALE_RECOVERY';return this.phase;}
 legalActions(o:ObligationObservation,candidates:LegalAction[],tick:number){const phase=this.observe(o,tick);if(phase==='SURVIVAL')return candidates.filter(a=>/^(eat|drink|retreat|walkTo|closeModal|useInventoryItem)$/.test(String(a.type)));if(phase==='STALE_RECOVERY')return candidates.filter(a=>/^(clickDialogOption|closeModal|closeShop|walkTo|travelToBank)$/.test(String(a.type)));if(phase==='LOOT_RESOLUTION')return candidates.filter(a=>/^(pickupItem|walkTo|travelToBank|bankDeposit|shopSell|closeModal)$/.test(String(a.type)));if(phase==='CAPACITY_RESOLUTION')return candidates.filter(a=>/^(travelToBank|walkTo|interactNpc|interactLoc|interactMerchant|openShop|openBank|bankDeposit|shopSell|useInventoryItem|dropItem|closeModal)$/.test(String(a.type))&&!unsafeUnderCapacity.test(String(a.type)));if(phase==='TRANSACTION'){const allowed=candidates.filter(a=>transaction.test(String(a.type))&&!/^(shopBuy|bankWithdraw)$/.test(String(a.type)));return this.noProgressAttempts>=2?allowed.filter(a=>/^(clickDialogOption|closeShop|closeModal)$/.test(String(a.type))):allowed;}return candidates.filter(a=>!unsafeUnderCapacity.test(String(a.type))||o.freeSlots>o.warningSlots);}
 begin(action:LegalAction,tick:number){this.lastAction=String(action.type);if(transaction.test(String(action.type)))this.transactionAttempts++;}
 verify(action:LegalAction,result:{inventoryChanged?:boolean;coinDelta?:number;moved?:boolean;success?:boolean},tick:number){const progressed=result.inventoryChanged===true||Number(result.coinDelta||0)!==0||result.moved===true;if(progressed){this.noProgressAttempts=0;this.lastProgressTick=tick;this.transactionAttempts=0;this.blockedUntilTick=0;}else if(transaction.test(String(action.type))){this.noProgressAttempts++;if(this.noProgressAttempts>=2)this.blockedUntilTick=tick+12;}if(result.success===false)this.noProgressAttempts++;return{progressed,phase:this.phase,noProgressAttempts:this.noProgressAttempts,blockedUntilTick:this.blockedUntilTick};}
 reset(reason='operator reset'){this.phase='EXPLORATION';this.transactionAttempts=0;this.noProgressAttempts=0;this.lastAction='';this.blockedUntilTick=0;return reason;}
}
